### PR TITLE
v2raya: presist user data

### LINKED ISSUE #1: 能否将v2raya的配置文件移至scoop/persist下以符合规范
如题

### PR DESCRIPTION
**Pull request by Ryanjiena**
1. v2raya/v2raya-git: presist user data(~/.config/v2raya) fix #1 
2. v2raya/v2raya-git: add shortcut(v2raya.ps1)
3. v2ray-rules-dat: install LoyalsoldierIP.dat
4. v2raya-git: fix 'scoopdir'

### CODE REVIEW

**Comment by mzz2017** [comment]
@Ryanjiena Thanks for your great work. However, I think it is hard to migrate all files and it may not satisfy the user's mind. I think we should obey the scoop's standard and use the scoop dir as config dir, but we just give a prompt to tell how to migrate. And the decision is in the hands of the user.

**Comment by Ryanjiena** [comment]
https://github.com/Ryanjiena/v2raya-scoop/blob/265fa1040e1a810f6303680ccdb54a7712646a15/bucket/v2raya.json#L20-L24

**Comment by MarksonHon** [comment]
@Ryanjiena Thank you for your pull request.However, V2RAY_LOCATION_ASSET must be set to be $(scoop prefix v2ray)  if you choose link them to v2ray's dir.

**Comment by Ryanjiena** [comment]
@MarksonHon done

**Comment by MarksonHon** [comment]
@Ryanjiena And then, I found two problems:
1. v2rayA CANNON run on no-Linux platforms if there is no --lite parameter, beacuse v2rayA is designed for Linux's transparent proxy originally so it requires root privilege on default. Using '--lite' parameter would disable transparent proxy feature so it can run on no-Linux platforms such as Windows, FreeBSD and macOS.
2. I think a command line software should have no shortcut, just like nano, curl or v2ray. A shortcut of a command line software would mislead users that they might think this program is not working at all even though program is running on the background.

**Comment by MarksonHon** [comment]
@Ryanjiena Have a nice day/night 😀

**Comment by MarksonHon** [comment]
Another problem:
If you want to save data to scoop's persist folder, you must set V2RAYA_CONFIG or '--config' arg to the persist folder, and it can only be set in scoop's 'bin' configuration.

**Comment by MarksonHon** [comment]
@MarksonHon And $env:scoop is NOT an available variable, according scoop's feature, I think use $(scoop prefix v2ray) is better.

**Comment by Ryanjiena** [comment]
......

> @Ryanjiena And then, I found two problems:
> 
> 1. v2rayA CANNON run on no-Linux platforms if there is no --lite parameter, beacuse v2rayA is designed for Linux's transparent proxy originally so it requires root privilege on default. Using '--lite' parameter would disable transparent proxy feature so it can run on no-Linux platforms such as Windows, FreeBSD and macOS.
> 2. I think a command line software should have no shortcut, just like nano, curl or v2ray. A shortcut of a command line software would mislead users that they might think this program is not working at all even though program is running on the background.

Done. Sorry that I forgot to check the documentation.

**Comment by Ryanjiena** [comment]
> If you want to save data to scoop's persist folder, you must set V2RAYA_CONFIG or '--config' arg to the persist folder, and it can only be set in scoop's 'bin' configuration.

The user data is still stored in the `$env:UserProfile\.config\v2raya` directory, scoop just copies it to the `$persist_dir\User Data` directory during installation/uninstallation.

> And $env:scoop is NOT an available variable, according scoop's feature, I think use $(scoop prefix v2ray) is better.

Scoop [doccument](https://github.com/ScoopInstaller/scoop/wiki/Pre--and-Post-install-scripts) : Base Scoop install dir (typically %USERPROFILE%\scoop, `%SCOOP% overrides)

**Comment by Ryanjiena** [comment]
> @Ryanjiena Have a nice day/night 😀

😂

**Comment by Ryanjiena** [comment]
> @MarksonHon And $env:scoop is NOT an available variable, according scoop's feature, I think use $(scoop prefix v2ray) is better.

https://github.com/ScoopInstaller/Install/blob/30337df072607761e274687428b0addd860c70e1/install.ps1#L527

**Comment by MarksonHon** [comment]
@Ryanjiena This is the installer of scoop itself but NOT for a app. 
For the variables of Pre and Post install scripts, and installation scripts, you should read the official wiki from scoop:

<https://github.com/ScoopInstaller/Scoop/wiki/Pre--and-Post-install-scripts>

**Comment by Ryanjiena** [comment]
> installed a Windows 10 in VM and add your fork to scoop, then I installed `v2ray-rules-dat`, and finally, v2rayA stopped.

image

**Comment by MarksonHon** [comment]
@Ryanjiena You customized the scoop installation directory, so $env:scoop may exist. But for users installing to the default directory, this variable is not available.

**Comment by Ryanjiena** [comment]
@MarksonHon  done，

**Comment by Ryanjiena** [comment]
.

**Comment by MarksonHon** [comment]
@Ryanjiena https://github.com/ScoopInstaller/Install/blob/30337df072607761e274687428b0addd860c70e1/install.ps1#L432

**Comment by Ryanjiena** [comment]
> @Ryanjiena [ScoopInstaller/Install@`30337df`/install.ps1#L432](https://github.com/ScoopInstaller/Install/blob/30337df072607761e274687428b0addd860c70e1/install.ps1#L432)

Yes,  using `$(appdir v2ray $global) ` 
image

**Comment by Ryanjiena** [comment]
我刚才在我同学电脑上测试一下，发现确实是这样的。之前安装 scoop 时都是使用先设置 `$env:SCOOP` 变量选择安装位置后安装，现在直接默认安装了

**Comment by MarksonHon** [comment]
@Ryanjiena 既然都会中文，那就中文继续吧。
目前有三点建议：
一、那两个启动服务的脚本不需要搭配 sudo 使用，因为 v2rayA 在非 Linux 环境或不使用透明代理的情况下不需要特别的权限。同时你这里面的 $env:scoop 还没拿掉，其实在这里直接写 $dir\\v2rayawin.exe 就好，最终生成的脚本里面将会包含符合最终用户情况的绝对路径。
二、结束进程的时候应当针对性地结束 v2rayawin.exe 或 v2rayawin-git.exe，而不应该通杀。
三、隐藏窗口后是看不到日志的，因此建议根据 v2rayA 的文档指定一个日志文件，可以将它放到 $env:TEMP。

**Comment by Ryanjiena** [comment]
> @Ryanjiena 既然都会中文，那就中文继续吧。 目前有三点建议： 一、那两个启动服务的脚本不需要搭配 sudo 使用，因为 v2rayA 在非 Linux 环境或不使用透明代理的情况下不需要特别的权限。同时你这里面的 $env:scoop 还没拿掉，其实在这里直接写 $dir\v2rayawin.exe 就好，最终生成的脚本里面将会包含符合最终用户情况的绝对路径。 二、结束进程的时候应当针对性地结束 v2rayawin.exe 或 v2rayawin-git.exe，而不应该通杀。 三、隐藏窗口后是看不到日志的，因此建议根据 v2rayA 的文档指定一个日志文件，可以将它放到 $env:TEMP。

好的~

**Comment by Ryanjiena** [comment]
越写越乱...... 现在在我本地测试通过了

**Comment by JaimeZeng** [comment]
你看的不是最新的

**Comment by MarksonHon** [comment]
> 你看的不是最新的

看到了最新的，那么那个启动脚本改下吧，我发现让 PowerShell 从 JSON 里面读取数据然后输出一个 PowerShell 脚本过于套娃，有些原本要写入脚本的参数被 Set-Content 自己读取了，$dir 这些变量在单括号里面也没发用。

可以试一下我改好的：
<https://wtools.io/paste-code/bBQx>

**Comment by Ryanjiena** [comment]
> 看到了最新的，那么那个启动脚本改下吧，我发现让 PowerShell 从 JSON 里面读取数据然后输出一个 PowerShell 脚本过于套娃，有些原本要写入脚本的参数被 Set-Content 自己读取了，$dir 这些变量在单括号里面也没发用。

这个是因为你仓库的原因😂，正常这种脚本会直接放在 scripts 目录下，安装时复制到目录

**Comment by Ryanjiena** [comment]
@MarksonHon 你直接使用 github review 吧🤣，我到现在眼睛都看花了......

**Comment by MarksonHon** [comment]
@Ryanjiena 我看了下，你那边的写得应该可以，就是缓存目录其实可以直接 $env:TEMP

**Comment by MarksonHon** [comment]
欢迎进群：
<https://t.me/v2raya_zh>

**Pull request merged**
